### ISSUE TITLE
wrong parsing "subject" (my working code)

### ISSUE THREAD

**Issue by SANYA-SNEX** [eXorus/php-mime-mail-parser#39] opened 2015-02-17 11:16 UTC
function convert_chars($char_code,$text_to_decode) {
if ($char_code == 'default' || $char_code == '' || $char_code == 'X-UNKNOWN'){
$text_to_decode=$text_to_decode;
} elseif (strtolower($char_code) == 'UTF-8') {
$text_to_decode=$text_to_decode;
} else {
$text_to_decode=iconv($char_code, "UTF-8//TRANSLIT", $text_to_decode);
} return $text_to_decode; }

$subject =$Parser->parts[1][headers][subject];
$decode = imap_mime_header_decode($subject);
$subject="";
foreach ($decode as $subject_part) {
$subject_part_decode=convert_chars($subject_part->charset,$subject_part->text);
$subject=$subject.$subject_part_decode;
}

**Comment by eXorus** [comment] 2015-02-17 12:22
Could you send me an mail sample that didn't work ?

**Comment by SANYA-SNEX** [comment] 2015-02-17 13:03
problem occurs when sabdzhekt very long and it is divided into an array, and your script Pars only the last element of the array!

for example try parse this email: (original subject is: "problem occurs when sabdzhekt very long and it is divided into an array, and your script Pars only the last element of the array! Путін хуйло!!!!!!")



------------------------
Return-Path: <mail@exemple.com>
Delivered-To: mail@exemple.com
Received: from [10.0.0.10] (unknown [10.0.0.10])
	by exemple.com (Postfix) with ESMTPS id 349EF25093
	for <mail@exemple.com>; Tue, 17 Feb 2015 14:58:39 +0200 (EET)
Date: Tue, 17 Feb 2015 14:58:38 +0200
From: mail@exemple.com
X-Priority: 3 (Normal)
Message-ID: <234332723.20150217145838@exemple.com>
To: mail@exemple.com, mail2@exemple3.com, mail3@exemple2.com
Subject: =?windows-1251?Q?problem_occurs_when_sabdzhekt_very_long_and_it_is_divided_into_an_array?=
 =?windows-1251?Q?=2C_and_your_script_Pars_only_the_last_element_of_the_array!_=CF=F3=F2?=
 =?windows-1251?Q?=B3=ED_=F5=F3=E9=EB=EE!!!!!!?=
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

mini plain body
------------------------

**Comment by eXorus** [comment] 2015-02-17 21:24
This is a duplicate of #3 
I have a good news for everyone, I think that have the solution. I will publish it very soon (this friday). It's working for all the cases:

사진.JPG
Keith Moore <moore@cs.utk.edu>
Keld Jørn Simonsen <keld@dkuug.dk>
André Pirard <PIRARD@vm1.ulg.ac.be>
If you can read this yo
u understand the example.
Mail avec fichier attaché de 1ko
Hello World !
, and your script Pars only the last element of the array! Пут
problem occurs when sabdzhekt very long and it is divided into an array
ін хуйло!!!!!!


Thanks for your help.

**Closed** 2015-02-20 13:16 UTC
