### ISSUE TITLE
php-mime-mail-parser truncating attachments

### ISSUE THREAD

**Issue by squareproton** [eXorus/php-mime-mail-parser#34] opened 2015-01-11 16:39 UTC
Whilst using php-mime-mail-parser to parse some emails and extract attachments. In two cases I've found php-mime-mail-parser truncating attachments. I've tested with Zend php email libs and it can extract the attachments correctly.

Unfortunately I can't attach the raw email here for privacy reasons. Should you want to look into this what is best way to share a raw email with you privately?

My email is squareproton@gmail.com.

**Comment by squareproton** [comment] 2015-01-11 18:19
Ok. So I've figured out what's happening and put in the workaround but I can't make any sense of it.

The attachment parsing is fine. It looks like a php weirdness.

The code in src/Parser, getAttachmentStream() is the culprit.
```
#!php
    $attachment = $this->decodeContentTransfer($this->getPartBodyFromText($part), $encodingType);
    fwrite($temp_fp, $attachment, strlen($attachment));
```

The attachment is being decoded correctly but the call to fwrite() doesn't write all the data to the stream. Initially I thought this might be something to do with http://stackoverflow.com/questions/9473474/php-fwrite-doesnt-finish-writing-string-data-to-file-why but it return the correct number of bytes. I've tested writing to the stream in small chunks, writing to a file created with `fopen(, 'w+')` instead of `tmpfile()` and various different methods of reading the stream all with out success.

In the end I've just changed the the function `getAttachmentStream()` to return the payload as a string and modified the access methods `src/Attachment.php` to handle this which has solved the problem. If I didn't think it was so unlikely I'd be claiming this as a php bug in fwrite. The attachment isn't large either at ~144KB. 

At this point I don't feel this is a problem in php-mime-mail-parser. I'll leave this as a open issue in case you want to do further work on this but I also feel this could now be safely closed.

**Comment by clementhk** [comment] 2015-01-12 03:37
Hi,

I do believe this is an issue because it affects real servers. 

Clement

**Comment by eXorus** [comment] 2015-01-12 12:33
Could you send me the raw email and the fix to see what I can do ?

**Comment by squareproton** [comment] 2015-01-14 20:53
Thanks for your responses. I'm not happy to attach the raw email file to this issue directly due to privacy reasons. If you ping me a email to squareproton@gmail.com or post your email addresses here I'd be happy to send this to you directly with the expectation that it didn't get distributed in any way, commited to a repo or added to a automated test suite, ...

Whilst I'm certain this is a problem which could effect others I'm 99% sure the problem _is not_ in php-mime-mail-parser and is likely a problem in some combination of `PHP 5.6.4-1+deb.sury.org~precise+1 (cli) (built: Dec 21 2014 19:26:25)` or `Ubuntu 12.04.5 LTS`. 

I pinned the problem to a failed call to php's `fwrite()`. Yeah I know. It doesn't make any sense. php-mime-mail-parser's code looks solid and I can't see what more you could possibly do other than change the design which is what I eventually did.

For the record my changes were

Parser.php. Removed $temp_fp and instead build attachment as string.
```
    /**
     * Read the attachment Body and save temporary file resource
     * @return String Mime Body Part
     * @param $part Array
     */
    private function getAttachmentStream(&$part)
    {
        $headers = $this->getPart('headers', $part);
        $encodingType = array_key_exists('content-transfer-encoding', $headers) ?
            $headers['content-transfer-encoding'] : '';

        $attachment_as_string = '';

        if ($this->stream) {
            $start = $part['starting-pos-body'];
            $end = $part['ending-pos-body'];
            fseek($this->stream, $start, SEEK_SET);
            $len = $end-$start;
            $written = 0;
            $write = 2028;
            while ($written < $len) {
                $write = $len;
                $part = fread($this->stream, $write);
                $attachment_as_string += $this->decodeContentTransfer($part, $encodingType);
                $written += $write;
            }
        } elseif ($this->data) {
            $attachment_as_string = $this->decodeContentTransfer($this->getPartBodyFromText($part), $encodingType);
        }

        return $attachment_as_string;
    }
```

Attachment.php. Mods to handle a contentString not a stream. Add class variable $streamPos initialised to 0 to track position for read()
```
    /**
    * Read the contents a few bytes at a time until completed
    * Once read to completion, it always returns false
    * @return String
    * @param $bytes Int[optional]
    */
    public function read($bytes = 2082)
    {
        if ($this->streamPos < strlen($this->content)) {
            $output = substr($this->content, $this->streamPos, $bytes);
            $this->streamPos += strlen($output);
            return $output;
        } else {
            return false;
        }
    }

    /**
    * Retrieve the file content in one go
    * Once you retreive the content you cannot use MimeMailParser_attachment::read()
    * @return String
    */
    public function getContent()
    {
        return $this->content;
    }
```

**Comment by eXorus** [comment] 2015-01-15 08:27
I send you twice my email 
11/01/2015 19:48
15/01/2015 09:20

I will not publish your raw email here don't worry.

**Comment by squareproton** [comment] 2015-01-15 22:22
Sorry eXorus. Have sent that off now.  15/01/2015 22:21 GMT.

**Comment by eXorus** [comment] 2015-02-20 13:49
Sorry I tried to reproduce the issue and fix it but I can't.

The 2 emails received (according to me) are correctly parsed and I can open it in PDF to see it. When I edit my code with your 3 new functions nothing worked. All the attachments with all my email test are KO and yours also (I can't open it and the size of the files are 0). 

You can send me your complete code with the email test parsed with my library and the email test parsed with your fix to compare them.

For the moment I'm closing this issue. Sorry

**Closed by eXorus** 2015-02-20 13:49 UTC
Labels: bug
